safe: true
# source: <your pages repo>
destination: _site
lsi: false
pygments: true
markdown:    rdiscount
rdiscount:   { extensions: [smart] }
permalink:   /:year/:month/:title/
url: http://jedfoster.com
exclude: config.ru, Gemfile, Gemfile.lock, Rakefile, html5-WP-audio-player/, AudioJS/, Readmore.js/, Sass-Deck/
include: js/
environments:
  github:
    url: http://jedfoster.github.com
  production:
    url: http://jedfoster.com
    remote:
      connection: jedfoste@jedfoster.com
      path: public_html/
