javascript_compressor: closure
package_path: "../js/"
gzip_assets: off

javascripts:
  prettify.min:
    - _js/prettify.js
    - _js/lang-css.js
    - _js/lang-scss.js
    - _js/lang-sql.js
    - _js/lang-vim.js
    - _js/lang-yaml.js
    - _js/prettify-loader.js
  audio-wp:
    - _js/audio-wp.js
  audio:
    - _js/audio.js
  jquery-1.8.2:
    - _js/jquery-1.8.2.js
  jquery.foundation.clearing:
    - _js/jquery.foundation.clearing.js
  modernizr:
    - _js/modernizr.js
  readmore.min:
    - _js/readmore.min.js
  notes:
    - _js/moment.min.js
    - _js/jquery-1.8.2.js
    - _js/notes.js


# stylesheets:
#   common:
#     - public/stylesheets/reset.css
#     - public/stylesheets/widgets/*.css
#   workspace:
#     - public/stylesheets/pages/workspace.css
#   empty:
#     - public/stylesheets/pages/empty.css
